// export const SEARCH_ANALYSE = "SEARCH_ANALYSE";
// export const SEARCH_ANALYSES = "SEARCH_ANALYSES";
// export const FETCH_ANALYSES = "FETCH_ANALYSES";
// export const FETCH_ANALYSES_REQS = "FETCH_ANALYSES_REQS";
// export const FETCH_ECHANTILLONNAGES = "FETCH_ECHANTILLONNAGES";
export const LOADING = "LOADING";

// Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

// SnackBar
export const SNACKBAR_SUCCESS = "SNACKBAR_SUCCESS";
export const SNACKBAR_CLEAR = "SNACKBAR_CLEAR";
export const SNACKBAR_ERROR = "SNACKBAR_ERROR";
