export const SEARCH_ANALYSE = "SEARCH_ANALYSE";
export const SEARCH_ANALYSES = "SEARCH_ANALYSES";
export const FETCH_ANALYSES = "FETCH_ANALYSES";
export const FETCH_ECHANTILLONNAGES = "FETCH_ECHANTILLONNAGES";
export const LOADING = "LOADING";
